In [1]:
import numpy as np

In [2]:
probabilities = np.array([9.5521e-01, 8.4898e-02, 5.0589e-03, 1.8228e-03])


In [3]:
np.sum(probabilities)

1.0469897000000001

In [ ]:
prob_5th_class = 1 - np.sum(probabilities)

In [4]:
import torch

In [16]:
logits = torch.tensor([[14.152, -6.1942, 0.47710, 0.96850],
                       [-0.152, -6.1942, 0.47710, 0.96850],
                     [65.667, 0.303, 11.500, -4.524]])


In [81]:
logits

tensor([[14.1520, -6.1942,  0.4771,  0.9685],
        [-0.1520, -6.1942,  0.4771,  0.9685],
        [65.6670,  0.3030, 11.5000, -4.5240]])

In [17]:

probas0 = torch.sigmoid(logits)
probas = torch.cumprod(probas0, dim=1)
predict_levels = probas > 0.5
predicted_labels = torch.sum(predict_levels, dim=1)

In [73]:
probas

tensor([[1.0000e+00, 2.0371e-03, 1.2570e-03, 9.1110e-04],
        [4.6207e-01, 9.4128e-04, 5.8083e-04, 4.2100e-04],
        [1.0000e+00, 5.7518e-01, 5.7517e-01, 6.1711e-03]])

In [18]:
probas0

tensor([[1.0000, 0.0020, 0.6171, 0.7248],
        [0.4621, 0.0020, 0.6171, 0.7248],
        [1.0000, 0.5752, 1.0000, 0.0107]])

In [40]:
# create a tensor of shape (1,3) of ones
ones = torch.ones((3,1))

probs1 = torch.concat([ones, probas], dim=1)

In [70]:
probs2 = np.hstack([np.ones((3,1)), probas.numpy()])
probs3 = np.hstack([np.diff(probs2, axis=1), probs2[:,-1].reshape(-1,1)])

In [72]:
probs2

array([[1.00000000e+00, 9.99999285e-01, 2.03707581e-03, 1.25700375e-03,
        9.11102048e-04],
       [1.00000000e+00, 4.62072998e-01, 9.41278355e-04, 5.80827938e-04,
        4.20995959e-04],
       [1.00000000e+00, 1.00000000e+00, 5.75175762e-01, 5.75169921e-01,
        6.17110683e-03]])

In [71]:
probs3

array([[-7.15255737e-07, -9.97962209e-01, -7.80072063e-04,
        -3.45901703e-04,  9.11102048e-04],
       [-5.37927002e-01, -4.61131720e-01, -3.60450416e-04,
        -1.59831980e-04,  4.20995959e-04],
       [ 0.00000000e+00, -4.24824238e-01, -5.84125519e-06,
        -5.68998814e-01,  6.17110683e-03]])

In [88]:
def logit(p):
    return np.log(p / (1 - p))

In [91]:
eps = 1e-6
probs2 = np.hstack([np.ones((3,1)), probas.numpy()])
probs3 = -1*np.hstack([np.diff(probs2, axis=1), -1*probs2[:,-1].reshape(-1,1)]) + eps
# probs4 = np.exp(probs3)
probs4 = logit(probs3)
# apply the softmax function to probs3
probs5 = np.exp(probs4) / np.sum(np.exp(probs4), axis=1).reshape(-1,1)



In [95]:
import torch
from torch.nn.functional import softmax

eps = 1e-6

# Assuming probas is a PyTorch tensor
probs2 = torch.cat([torch.ones((probas.size(0),1)), probas], dim=1)
probs3 = -1 * torch.cat([torch.diff(probs2, dim=1), -1 * probs2[:,-1].unsqueeze(1)], dim=1) + eps

# Define the logit function
def logit(p):
    return torch.log(p / (1 - p))

probs4 = logit(probs3)

# Apply the softmax function to probs4
probs5 = softmax(probs4, dim=1)

In [96]:
probs5

tensor([[3.5007e-09, 1.0000e+00, 1.5953e-06, 7.0824e-07, 1.8632e-06],
        [5.7608e-01, 4.2346e-01, 1.7892e-04, 7.9599e-05, 2.0891e-04],
        [4.8426e-07, 3.5768e-01, 3.3130e-06, 6.3931e-01, 3.0075e-03]])

In [92]:
probs5

array([[3.50073927e-09, 9.99995830e-01, 1.59536696e-06, 7.08251096e-07,
        1.86324461e-06],
       [5.76075700e-01, 4.23456867e-01, 1.78924902e-04, 7.95989459e-05,
        2.08908763e-04],
       [4.84260835e-07, 3.57675670e-01, 3.31297130e-06, 6.39313064e-01,
        3.00746903e-03]])

In [86]:
probs5

array([[0.16666679, 0.3329937 , 0.16679668, 0.16672432, 0.16681852],
       [0.25632117, 0.24352195, 0.16672674, 0.16669331, 0.16673683],
       [0.16666667, 0.23747071, 0.16666764, 0.2614998 , 0.16769518]])

In [80]:
probs4

array([[1.00000072, 2.71274818, 1.00078038, 1.00034596, 1.00091152],
       [1.71245327, 1.58586773, 1.00036052, 1.00015984, 1.00042108],
       [1.        , 1.5293216 , 1.00000584, 1.76649757, 1.00619019]])

In [79]:
probs5

array([[0.10475362, 0.58077219, 0.10483532, 0.10478979, 0.10484907],
       [0.29825113, 0.2627887 , 0.14632689, 0.14629753, 0.14633575],
       [0.14585317, 0.24762661, 0.14585402, 0.31390738, 0.14675882]])

In [75]:
probs3

array([[ 7.15255737e-07,  9.97962209e-01,  7.80072063e-04,
         3.45901703e-04,  9.11102048e-04],
       [ 5.37927002e-01,  4.61131720e-01,  3.60450416e-04,
         1.59831980e-04,  4.20995959e-04],
       [-0.00000000e+00,  4.24824238e-01,  5.84125519e-06,
         5.68998814e-01,  6.17110683e-03]])

In [58]:
np.diff(probs2, axis=1)

array([[-7.15255737e-07, -9.97962209e-01, -7.80072063e-04,
        -3.45901703e-04],
       [-5.37927002e-01, -4.61131720e-01, -3.60450416e-04,
        -1.59831980e-04],
       [ 0.00000000e+00, -4.24824238e-01, -5.84125519e-06,
        -5.68998814e-01]])

In [59]:
probs2[:,-1]

array([0.0009111 , 0.000421  , 0.00617111])

In [60]:
probs1[:,0]- probs1[:,1]



tensor([7.1526e-07, 5.3793e-01, 0.0000e+00])

In [61]:
probs1[:,1]- probs1[:,2]

tensor([0.9980, 0.4611, 0.4248])

In [62]:
probs1[:,2]- probs1[:,3]

tensor([7.8007e-04, 3.6045e-04, 5.8413e-06])

In [63]:
probs1[:,3]- probs1[:,4]

tensor([3.4590e-04, 1.5983e-04, 5.6900e-01])

In [64]:
probs1[:,4]

tensor([0.0009, 0.0004, 0.0062])

In [65]:
predicted_labels

tensor([1, 0, 3])