In [1]:
## Test The new multi-head models

In [1]:
import os
import pandas as pd
import torch
from models import Binary_Head, MultiClass_Head, MultiHead


In [2]:
data_dir= '/DATA2'
X_file = os.path.join(data_dir, 'X_finetune_trainval.csv')
y_file = os.path.join(data_dir, 'y_finetune_trainval.csv')


In [20]:
X_df = pd.read_csv(X_file, index_col=0)
y_df = pd.read_csv(y_file, index_col=0)

In [24]:
y_df[].shape

SyntaxError: invalid syntax (448899414.py, line 1)

In [22]:
y_df[[]].shape

(592, 0)

In [23]:
y_df[[]].size

0

In [4]:
y_df.head()

cohort_id  Study ID  Cohort Label  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML         541  ST001237  adult_cancer   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML        541  ST001237  adult_cancer   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML         541  ST001237  adult_cancer   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML         541  ST001237  adult_cancer   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML         541  ST001237  adult_cancer   

                                            Cohort ID         OS  OS_Event  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML         541   3.614000       1.0   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML        541   3.909700       1.0   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML         541  50.759754       0.0   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML         541  31.047228       1.0   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML         541   1.938400       1.0   

                                             Age        subject ID study_week  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML   64.0  CA209025-125-525   baseline   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML  65.0  CA209025-108-510   baseline   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML   57.0  CA209025-84-1041   baseline   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML   69.0   CA209025-75-615   baseline   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML   68.0   CA209025-114-60   baseline   

                                                    Region  ...  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML    REST OF WORLD  ...   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML   REST OF WORLD  ...   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML    REST OF WORLD  ...   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML   WESTERN EUROPE  ...   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML   WESTERN EUROPE  ...   

                                           Benefit ORDINAL  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML              0.0   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML             1.0   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML              2.0   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML              2.0   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML              1.0   

                                           Nivo Benefit BINARY  MSKCC BINARY  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML                  NaN           0.0   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML                 NaN           NaN   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML                  1.0           NaN   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML                  1.0           1.0   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML                  NaN           NaN   

                                           MSKCC ORDINAL Matt Set       Set  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML            0.0    Train  Finetune   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML           1.0    Train  Finetune   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML            1.0    Train  Finetune   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML            2.0    Train  Finetune   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML            1.0    Train  Finetune   

                                            Pretrain  is Pediatric  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML        NaN         False   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML       NaN         False   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML        NaN         False   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML        NaN         False   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML        NaN         False   

                                            Cohort Label ENC Study ID ENC  
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML                  0            4  
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML                 0            4  
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML                  0            4  
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML                  0            4  
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML                  0        

In [5]:
X = torch.tensor(X_df.values, dtype=torch.float32)
y = torch.tensor(y_df[['MSKCC BINARY','Benefit ORDINAL']].values, dtype=torch.float32)

In [6]:
model1 = Binary_Head(name='mskcc')
model2 = MultiClass_Head(name='benefit',y_idx=1,num_classes=3)

model1.define_architecture(input_size=X.shape[1],output_size=1)
model2.define_architecture(input_size=X.shape[1])


In [7]:
model = MultiHead([model1,model2])

In [8]:
model1.get_hyperparameters()

{'training': True,
 'goal': 'classify',
 'kind': 'Binary',
 'name': 'mskcc',
 'y_idx': 0,
 'weight': 1.0,
 'input_size': 2736,
 'output_size': 1,
 'architecture': {'input_size': 2736, 'output_size': 1},
 'score_func_dict': {'AUROC': BinaryAUROC()},
 'class_weight': None,
 'pos_class_weight': None,
 'loss_reduction': 'mean'}

In [9]:
model

MultiHead(
  (heads): ModuleList(
    (0): Binary_Head(
      (network): Dense_Layers(
        (network): Sequential(
          (0): Linear(in_features=2736, out_features=1, bias=True)
          (1): LeakyReLU(negative_slope=0.01)
          (2): Dropout(p=0.2, inplace=False)
          (output_layer): Sequential(
            (0): Linear(in_features=1, out_features=1, bias=True)
          )
        )
      )
      (loss_func): BCEWithLogitsLoss()
    )
    (1): MultiClass_Head(
      (network): Dense_Layers(
        (network): Sequential(
          (0): Linear(in_features=2736, out_features=1, bias=True)
          (1): LeakyReLU(negative_slope=0.01)
          (2): Dropout(p=0.2, inplace=False)
          (output_layer): Sequential(
            (0): Linear(in_features=1, out_features=3, bias=True)
          )
        )
      )
      (loss_func): CrossEntropyLoss()
    )
  )
)

In [10]:
outputs = model(X[0:10])

In [16]:
X[0:10,:]

tensor([[-0.7825,  1.3744, -1.0287,  ...,  0.7922,  2.7728, -0.3425],
        [-0.7808,  1.3782, -1.0278,  ...,  0.7960,  2.7761,  0.1011],
        [-0.6111, -0.6626, -0.9367,  ...,  1.3224,  0.6127,  4.1957],
        ...,
        [-0.7231, -0.1691, -0.9968,  ...,  0.2307, -0.2754,  0.4597],
        [-0.8070,  1.3180, -1.0418,  ...,  0.7360,  2.7243,  0.2705],
        [-0.7667,  0.9259, -1.0202,  ...,  2.1577,  2.8040, -0.8570]])

In [18]:
y[0:10,:]

tensor([[0., 0.],
        [nan, 1.],
        [nan, 2.],
        [1., 2.],
        [nan, 1.],
        [0., 0.],
        [nan, 1.],
        [0., 1.],
        [nan, 2.],
        [0., 1.]])

In [14]:
y[0:10]

tensor([[0., 0.],
        [nan, 1.],
        [nan, 2.],
        [1., 2.],
        [nan, 1.],
        [0., 0.],
        [nan, 1.],
        [0., 1.],
        [nan, 2.],
        [0., 1.]])

In [11]:
model.score(outputs,y[0:10,:])

{'Binary_mskcc': {'AUROC': tensor(0.5000)},
 'MultiClass_benefit': {'AUROC': tensor(0.2600)}}

In [12]:
model.loss(outputs,y[0:10,:])

tensor(1.8532, grad_fn=<AddBackward0>)

In [13]:
model.multi_loss(outputs,y[0:10,:])

{'Binary_mskcc': tensor(0.5753, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>),
 'MultiClass_benefit': tensor(1.2779, grad_fn=<NllLossBackward0>)}

In [18]:
model.save_info(data_dir)

In [16]:
X.shape

torch.Size([592, 2736])

In [19]:
y[:10,:]

tensor([[0.],
        [nan],
        [nan],
        [1.],
        [nan],
        [0.],
        [nan],
        [0.],
        [nan],
        [0.]])

In [22]:
model.loss(output, y[:10,:])

tensor(0.8890, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [23]:
model.score(output, y[:10,:])

tensor(1.)

In [24]:
model.get_hyperparameters()

In [9]:
model1.save_info(data_dir)

In [19]:
model.save_state(data_dir)

In [26]:
import numpy as np


In [27]:
my_temp = [1,2,3,5]

np.array(my_temp)[[1,3]]

array([2, 5])

In [29]:
pd.Series(my_temp).iloc[[1,3]]

1    2
3    5
dtype: int64

In [30]:
model1.y_idx

0

In [31]:
model1.name

'mskcc'

In [36]:
outputs['MultiClass_benefit'].tolist()

[[0.868815004825592, 0.7470402717590332, 0.40934106707572937],
 [0.4383719265460968, 0.029471123591065407, -0.8120167255401611],
 [0.4430046081542969, 0.037194013595581055, -0.7988717555999756],
 [0.44112923741340637, 0.03406766802072525, -0.8041930198669434],
 [0.46984803676605225, 0.08194328099489212, -0.722705066204071],
 [0.5655702352523804, 0.24151675403118134, -0.451098769903183],
 [0.44120195508003235, 0.03418891876935959, -0.803986668586731],
 [0.4468335807323456, 0.043577101081609726, -0.7880072593688965],
 [0.4407656788825989, 0.033461589366197586, -0.8052246570587158],
 [0.4405214190483093, 0.03305443748831749, -0.8059176206588745]]

In [37]:
y_df.head()

cohort_id  Study ID  Cohort Label  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML         541  ST001237  adult_cancer   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML        541  ST001237  adult_cancer   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML         541  ST001237  adult_cancer   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML         541  ST001237  adult_cancer   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML         541  ST001237  adult_cancer   

                                            Cohort ID         OS  OS_Event  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML         541   3.614000       1.0   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML        541   3.909700       1.0   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML         541  50.759754       0.0   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML         541  31.047228       1.0   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML         541   1.938400       1.0   

                                             Age        subject ID study_week  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML   64.0  CA209025-125-525   baseline   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML  65.0  CA209025-108-510   baseline   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML   57.0  CA209025-84-1041   baseline   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML   69.0   CA209025-75-615   baseline   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML   68.0   CA209025-114-60   baseline   

                                                    Region  ...  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML    REST OF WORLD  ...   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML   REST OF WORLD  ...   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML    REST OF WORLD  ...   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML   WESTERN EUROPE  ...   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML   WESTERN EUROPE  ...   

                                           Benefit ORDINAL  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML              0.0   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML             1.0   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML              2.0   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML              2.0   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML              1.0   

                                           Nivo Benefit BINARY  MSKCC BINARY  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML                  NaN           0.0   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML                 NaN           NaN   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML                  1.0           NaN   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML                  1.0           1.0   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML                  NaN           NaN   

                                           MSKCC ORDINAL Matt Set       Set  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML            0.0    Train  Finetune   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML           1.0    Train  Finetune   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML            1.0    Train  Finetune   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML            2.0    Train  Finetune   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML            1.0    Train  Finetune   

                                            Pretrain  is Pediatric  \
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML        NaN         False   
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML       NaN         False   
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML        NaN         False   
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML        NaN         False   
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML        NaN         False   

                                            Cohort Label ENC Study ID ENC  
0092_Marios_PD1_Inhib2_HP-L1366505-7.mzML                  0            4  
0432_Marios_PD1_Inhib2_HP-EA185078-17.mzML                 0            4  
0487_Marios_PD1_Inhib2_HP-L1443422-9.mzML                  0            4  
0077_Marios_PD1_Inhib2_HP-E9479165-7.mzML                  0            4  
1090_Marios_PD1_Inhib2_HP-E9123055-7.mzML                  0        